@startuml
!if %variable_exists("RELATIVE_INCLUDE")
!include %get_variable_value("RELATIVE_INCLUDE")/C4_Context.puml
!else
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!endif

!if %variable_exists("RELATIVE_INCLUDE")
!define DEVICONS %get_variable_value("RELATIVE_INCLUDE")/../plantuml-icon-font-sprites/devicons
!define FONTAWESOME %get_variable_value("RELATIVE_INCLUDE")/../plantuml-icon-font-sprites/font-awesome-5
!else
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!endif

!include FONTAWESOME/users.puml


LAYOUT_TOP_DOWN()
' LAYOUT_AS_SKETCH()
LAYOUT_WITH_LEGEND()

Person(customer, "Customer", "Vehicle Driver and Passenger", $sprite="users")

System_Boundary(cdc, "Smart Cockpit System") {
  System(hut, "HUT", "Smart Cockpit Domain Controller")
  System_Ext(tbox, "T-Box", "Telematics-Box")
  System_Ext(etc, "ETC", "Electronic Toll Collection")
  System_Ext(hud, "HUD/AR-HUD", "Heads-up Display")
  System_Ext(whud, "W-HUD", "Windshield Heads-up Display")
  System_Ext(display, "IVI/Passenger/Cluser", "Display Screen")
  System_Ext(wifi_display, "RSE", "Rear Display Screen")

  Rel(hut, tbox, "Access Internet","SC-CANFD/1GE-T1")
  Rel(hut, etc, "Control","CAN")
  Rel(hut, hud, "Control","CAN")
  Rel(hut, whud, "Drive/Control","FP DLINK/I2C")
  Rel(hut, display, "Drive/Control","FP DLINK/I2C")
  Rel(hut, wifi_display, "Drive/Control","WIFI")
}

System_Ext(ccu, "CCU", "Central Computing Unit (EE4.0 only)")
System_Ext(gw, "GW", "Central Computing Unit (EE3.X only)")

Rel_R(customer, hut, "Interact","Display/Touch/Speech/Camera etc.")

Rel(ccu, hut, "Control","SC-CANFD/1GE-T1")
Rel(gw, hut, "Control","SC-CANFD/1GE-T1")


' Lay_D(customer, hut)

@enduml