!if %variable_exists("RELATIVE_INCLUDE")
  !define DEVICONS %get_variable_value("RELATIVE_INCLUDE")/../plantuml-icon-font-sprites/devicons
  !define FONTAWESOME %get_variable_value("RELATIVE_INCLUDE")/../plantuml-icon-font-sprites/font-awesome-5
!else
  !define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
  !define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!endif

!include FONTAWESOME/users.puml

UpdateEnterpriseBoundaryStyle($bgColor="gold", $fontColor="brown", $borderColor="brown")

' skinparam wrapWidth auto
skinparam wrapWidth 200
skinparam Backgroundcolor transparent
skinparam defaultTextAlignment center
skinparam fixCircleLabelOverlapping true

!$language = %get_variable_value("language")

!$ee_arch = %get_variable_value("EE_ARCH")

!$log_level = %get_variable_value("LOG_LEVEL")

' utility function
!unquoted function $get($idx, $array)
    !foreach $ecu in $array
        !if $ecu.idx == $idx
            !return $ecu
        !endif
    !endfor
!endfunction

!unquoted procedure $logDebug($log)
  !if ($log_level == "debug") 
    !log $log
  !endif
!endprocedure

!unquoted procedure $logInfo($log)
  !if ($log_level == "info") 
    !log $log
  !endif
!endprocedure